
a1 = Artist.create(name: "The Beatles", description: "The Beatles were an English rock band formed in Liverpool in 1960. With members John Lennon, Paul McCartney, George Harrison and Ringo Starr, they became widely regarded as the foremost and most influential music band in history, integral to pop music's evolution into an art form and to the development of the counterculture of the 1960s. Rooted in skiffle, beat and 1950s rock and roll, the group later experimented with several musical styles, ranging from pop ballads and Indian music to psychedelia and hard rock, often incorporating classical elements and unconventional recording techniques in innovative ways.", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Beatles_ad_1965_just_the_beatles_crop.jpg/220px-Beatles_ad_1965_just_the_beatles_crop.jpg")

d1 = Lp.create(name: "Please Please Me", description: "Please Please Me is the debut studio album by the English rock band the Beatles. Parlophone rush-released the album on 22 March 1963 in the United Kingdom to capitalise on the success of the band's singles Please Please Me (number 1 on most charts, although only number 2 on Record Retailer, later the UK Singles Chart) and Love Me Do (number 17). The album topped Record Retailer's LP chart for 30 weeks, an unprecedented achievement for a pop album at that time.", url: "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/tile/image/PleasePleaseMe_1.jpg")
d2 = Lp.create(name: "With the Beatles", description: "With the Beatles is the second studio album by the English rock band the Beatles. It was released on 22 November 1963, on Parlophone, and was recorded four months after the band's debut Please Please Me. The album features eight original compositions (seven by Lennon–McCartney and Don't Bother Me, George Harrison's first recorded solo composition and his first released on a Beatles album) and six covers (mostly of Motown, rock and roll, and R&B hits). The cover photograph was taken by the fashion photographer Robert Freeman, and it has been mimicked by several music groups over the years.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/0/0a/Withthebeatlescover.jpg/220px-Withthebeatlescover.jpg")
d3 = Lp.create(name: "A Hard Day's Night", description: "A Hard Day's Night is the third studio album by the English rock band the Beatles, released on 10 July 1964, with side one containing songs from the soundtrack to their film of the same name. The American version of the album was released two weeks earlier, on 26 June 1964 by United Artists Records, with a different track listing. In contrast to their first two albums, all 13 tracks on A Hard Day's Night were written by John Lennon and Paul McCartney showcasing the development of their songwriting talents. The album includes the title track, with its distinct opening chord, and the previously released Can't Buy Me Love, both transatlantic number-one singles for the band.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/e/e6/HardDayUK.jpg/220px-HardDayUK.jpg")
d4 = Lp.create(name: "Beatles for Sale", description: "Beatles for Sale is the fourth studio album by the English rock band the Beatles. It was released on 4 December 1964 in the United Kingdom on EMI's Parlophone label. Eight of the album's fourteen tracks appeared on Capitol Records' concurrent release, Beatles '65, issued in North America only. The album marked a departure from the upbeat tone that had characterised the Beatles' previous work, partly due to the band's exhaustion after a series of tours that had established them as a worldwide phenomenon in 1964. The songs introduced darker musical moods and more introspective lyrics, with John Lennon adopting an autobiographical perspective in compositions such as I'm a Loser and No Reply. The album also reflected the twin influences of country music and Bob Dylan, whom the Beatles met in New York in August 1964.", url: "https://img.discogs.com/V-SAT3bnxBRpT8AcskWVMrG2atI=/fit-in/600x600/filters:strip_icc():format(jpeg):mode_rgb():quality(90)/discogs-images/R-1816943-1343570952-2557.jpeg.jpg")
d5 = Lp.create(name: "Help!", description: "Help! is the fifth studio album by English rock band the Beatles and the soundtrack from their film Help!. It was released on 6 August 1965. Produced by George Martin, it was the fifth UK album release by the band, and contains fourteen songs in its original British form. Seven of these, including the singles Help! and Ticket to Ride, appeared in the film and took up the first side of the vinyl album. The second side contained seven other releases including the most-covered song ever written, Yesterday", url: "https://img.discogs.com/xrpfUSgkv011ISxZz6vs3z9mHTw=/fit-in/300x300/filters:strip_icc():format(jpeg):mode_rgb():quality(40)/discogs-images/R-2473361-1286014066.jpeg.jpg")
d6 = Lp.create(name: "Rubber Soul", description: "Rubber Soul is the sixth studio album by the English rock band the Beatles. It was released on 3 December 1965 in the United Kingdom, on EMI's Parlophone label, accompanied by the non-album double A-side single Day Tripper / We Can Work It Out. The original North American version of the album was altered by Capitol Records to include a different selection of tracks. Rubber Soul met with a highly favourable critical response and topped record charts in Britain and the United States for several weeks.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/7/74/Rubber_Soul.jpg/220px-Rubber_Soul.jpg")
d7 = Lp.create(name: "Revolver", description: "Revolver is the seventh studio album by the English rock band the Beatles. Released on 5 August 1966, it was the Beatles' final recording project before their retirement as live performers and marked the group's most overt use of studio technology up to that time, building on the advances of their late 1965 release Rubber Soul. The album's diverse sounds include tape loops and backwards recordings on the psychedelic Tomorrow Never Knows, a classical string octet on Eleanor Rigby, and Indian-music backing on Love You To. The album was reduced to eleven songs by Capitol Records in North America, where three of its tracks instead appeared on the June 1966 release Yesterday and Today.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/1/16/Revolver.jpg/220px-Revolver.jpg")
d8 = Lp.create(name: "Sgt. Pepper's Lonely Hearts Club Band", description: "Sgt. Pepper's Lonely Hearts Club Band is the eighth studio album by the English rock band the Beatles. Released on 26 May 1967 in the United Kingdom and 2 June 1967 in the United States, it spent 27 weeks at number one on the UK Albums Chart and 15 weeks at number one in the US. It was lauded by critics for its innovations in production, songwriting and graphic design, for bridging a cultural divide between popular music and high art, and for providing a musical representation of its generation and the contemporary counterculture. It won four Grammy Awards in 1968, including Album of the Year, the first rock LP to receive this honour.", url: "https://images-na.ssl-images-amazon.com/images/I/619A%2BlTIqIL._SY355_.jpg")
d9 = Lp.create(name: "Magical Mystery Tour", description: "Magical Mystery Tour is an album by the English rock band the Beatles that was released as a double EP in the United Kingdom and an LP in the United States. Produced by George Martin, it includes the soundtrack to the 1967 film of the same name. The EP was issued in the UK on 8 December 1967 on the Parlophone label, while the Capitol Records LP release in the US occurred on 27 November and featured eleven tracks with the addition of songs from the band's 1967 singles. The first release as an eleven-track LP in the UK did not occur until 1976.", url: "https://d2s36jztkuk7aw.cloudfront.net/sites/default/files/styles/tile_2_column/public/tile/image/original_462.jpg?itok=w2vK_LMN&timestamp=1354886431")
d10 = Lp.create(name: "The Beatles", description: "The Beatles, known as The White Album, is the ninth studio album by the English rock band the Beatles, released on 22 November 1968. A double album, its plain white sleeve has no graphics or text other than the band's name embossed, which was intended as a direct contrast to the vivid cover artwork of the band's previous LP Sgt. Pepper's Lonely Hearts Club Band. Although no singles were issued from The Beatles in Britain and the United States, the songs Hey Jude and Revolution originated from the same recording sessions and were issued on a single in August 1968. The album's songs range in style from British blues and ska to tracks influenced by Chuck Berry and Karlheinz Stockhausen.", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/2/20/TheBeatles68LP.jpg/200px-TheBeatles68LP.jpg")
d11 = Lp.create(name: "Yellow Submarine", description: "Yellow Submarine is the tenth studio album by English rock band the Beatles, released on 13 January 1969 in the United States and on 17 January 1969 in the United Kingdom. It was issued as the soundtrack to the animated film of the same name, which premiered in London in July 1968. The album contains six songs by the Beatles, including four new songs and the previously released Yellow Submarine and All You Need Is Love. The remainder of the album is a re-recording of the film's orchestral soundtrack by the band's producer, George Martin.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/a/ac/TheBeatles-YellowSubmarinealbumcover.jpg/220px-TheBeatles-YellowSubmarinealbumcover.jpg")
d12 = Lp.create(name: "Abbey Road", description: "Abbey Road is the eleventh studio album by English rock band the Beatles, released on 26 September 1969 by Apple Records. The recording sessions for the album were the last in which all four Beatles participated. Although Let It Be was the final album that the Beatles completed before the band's dissolution in April 1970, most of the album had been recorded before the Abbey Road sessions began. A two-sided hit single from the album, Something backed with Come Together, released in October, topped the Billboard Hot 100 chart in the US.", url: "https://ep01.epimg.net/cultura/imagenes/2018/07/24/actualidad/1532425585_576338_1532429307_noticia_normal.jpg")
d13 = Lp.create(name: "Let It Be", description: "Let It Be is the twelfth and final studio album by the English rock band the Beatles. It was released on 8 May 1970, almost a month after the group's break-up. Like most of the band's previous releases, it was a number one album in many countries, including both the US and the UK, and was released in tandem with the motion picture of the same name.", url: "http://discoclasico.com/202-thickbox_default/the-beatles-let-it-be-lp-nuevo-180-.jpg")

a1.lps << [d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, d13]



a2 = Artist.create(name: "Rihanna", description: "Robyn Rihanna Fenty (born 20 February 1988) is a Barbadian singer, businesswoman, diplomat, actress, dancer, and songwriter. Born in Saint Michael, Barbados, and raised in Bridgetown, she was discovered by American record producer Evan Rogers in her home country of Barbados in 2003. Throughout 2004, she recorded demo tapes under the direction of Rogers and signed a recording contract with Def Jam Recordings after auditioning for its then-president, hip hop producer and rapper Jay-Z. In 2005, Rihanna rose to fame with the release of her debut studio album Music of the Sun and its follow-up A Girl like Me (2006), which charted on the top 10 of the US Billboard 200 and respectively produced the successful singles Pon de Replay, SOS and Unfaithful", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7f/Rihanna.jpg/434px-Rihanna.jpg")

d1 = Lp.create(name: "Music of the Sun", description: "Music of the Sun is the debut studio album by Barbadian singer Rihanna. It was released on August 30, 2005 in the United States through Def Jam Recordings. Prior to signing with Def Jam, Rihanna was discovered by record producer Evan Rogers in Barbados, who helped Rihanna record demo tapes to send out to several record labels. Jay-Z, the former chief executive officer (CEO) and president of Def Jam, was given Rihanna's demo by Jay Brown, his A&R at Def Jam, and invited her to audition for the label after hearing what turned out to be her first single, Pon de Replay. She auditioned for Jay-Z and L.A. Reid, the former CEO and president of record label group The Island Def Jam Music Group, and was signed on the spot to prevent her from signing with another record label.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/6/6e/Rihanna_-_Music_of_the_Sun.png/220px-Rihanna_-_Music_of_the_Sun.png")
d2 = Lp.create(name: "A Girl like Me", description: "A Girl like Me is the second studio album by Barbadian singer Rihanna. It was released on April 10, 2006 by Def Jam Recordings. For the production of the album, Rihanna worked with Evan Rogers, Carl Sturken, StarGate, J. R. Rotem and label-mate Ne-Yo, who wrote the album's second single. A Girl like Me is a pop, reggae and R&B album influenced by Rihanna's Caribbean roots. The album also incorporates elements of dancehall and rock, as well as ballads, which music critics were ambivalent towards.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/6/61/A_Girl_like_Me_-_Rihanna.png/220px-A_Girl_like_Me_-_Rihanna.png")
d3 = Lp.create(name: "Good Girl Gone Bad", description: "Good Girl Gone Bad is the third studio album by singer Rihanna. It was released on May 31, 2007, by Def Jam Recordings and SRP Records. Rihanna worked with various producers on the album, including Christopher Tricky Stewart, Terius Dream Nash, Neo da Matrix, Timbaland, Carl Sturken, Evan Rogers and StarGate. Inspired by Brandy Norwood's fourth studio album Afrodisiac (2004), Good Girl Gone Bad is a pop, dance-pop and R&B album with 1980s music influences. Described as a turning point in Rihanna's career, it represents a departure from the Caribbean sound of her previous releases, Music of the Sun (2005) and A Girl like Me (2006). Apart from the sound, she also endorsed a new image for the release going from an innocent girl to an edgier and more sexual look.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f7/Good_Girl_Gone_Bad.png/220px-Good_Girl_Gone_Bad.png")
d4 = Lp.create(name: "Rated R", description: "Rated R is the fourth studio album by Barbadian singer Rihanna. It was released on November 20, 2009 by Def Jam Recordings and SRP Records. Recording sessions for the album began in April 2009 and took place at several recording studios throughout United States and Europe. Rihanna, together with Antonio L.A. Reid and The Carter Administration, was the executive producer of the album and worked with various record producers, including Chase & Status, StarGate, The-Dream, Ne-Yo, and Brian Kennedy. The record featured several vocalists and instrumentalists, including Young Jeezy, will.i.am, Justin Timberlake and Slash, who played the guitars in Rockstar 101", url: "https://upload.wikimedia.org/wikipedia/en/thumb/a/aa/Rihanna_-_Rated_R.png/220px-Rihanna_-_Rated_R.png")
d5 = Lp.create(name: "Loud", description: "Loud is the fifth studio album by Barbadian singer Rihanna. It was released on November 12, 2010, by Def Jam Recordings and SRP Records. It was recorded between February and August 2010, during the singer's Last Girl on Earth Tour and the filming of her first feature film Battleship. Rihanna was the executive producer of Loud and worked with various record producers, including StarGate, Sandy Vee, The Runners, Tricky Stewart and Alex da Kid. The album features several guest vocalists, including rappers Drake, Nicki Minaj and Eminem, who is featured on the sequel to Love the Way You Lie, titled Love the Way You Lie (Part II)", url: "https://upload.wikimedia.org/wikipedia/en/thumb/d/d1/Rihanna_-_Loud.png/220px-Rihanna_-_Loud.png")
d6 = Lp.create(name: "Talk That Talk", description: "Talk That Talk is the sixth studio album by Barbadian singer Rihanna, released on November 18, 2011, by Def Jam Recordings and SRP Records. It was recorded while traveling for the Loud Tour between February and November 2011, and was originally planned to be a reissue of her previous studio album Loud (2010). As executive producer, Rihanna enlisted a wide range of producers including Alex da Kid, Calvin Harris, Chase & Status, No I.D., and StarGate to achieve her desired sound. Following in the same vein as Loud, Talk That Talk is a dance-oriented pop/R&B crossover album that incorporates elements of hip hop, dubstep, electronic and house music. The album also continues to have subtle dancehall genres, whilst its lyrical content and themes revolve around a nihilist, romantic and lascivious lover.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/2/27/TalkThatTalkCover.png/220px-TalkThatTalkCover.png")
d7 = Lp.create(name: "Unapologetic", description: "Unapologetic is the seventh studio album by Barbadian singer Rihanna. It was released on November 19, 2012, by Def Jam Recordings and SRP Records. It was recorded between June and November 2012, during promotion of her sixth album, Talk That Talk (2011). As executive producer, Rihanna enlisted previous collaborators The-Dream, David Guetta, Chase & Status, and StarGate to work alongside new collaborators such as Parker Ighile, Mike Will Made-It, and Labrinth. Unapologetic is mainly a pop, dubstep and R&B album that incorporates elements of hip hop, EDM and reggae in its production, similar to the sound of her previous albums Talk That Talk (2011) and Rated R (2009).", url: "https://upload.wikimedia.org/wikipedia/en/thumb/9/9b/Unapologetic_-_Rihanna.png/220px-Unapologetic_-_Rihanna.png")
d8 = Lp.create(name: "Anti", description: "Anti (stylized in all caps) is the eighth studio album by Barbadian singer Rihanna. It was released on January 27, 2016, through Westbury Road and Roc Nation. The singer began planning the record in 2014, at which time she left her previous label Def Jam and joined Roc Nation. Work continued into 2015, during which she released three singles including FourFiveSeconds, which reached the top 10 in several markets; they were ultimately removed from the final track listing. Anti was made available for free digital download on January 27 through Tidal and was released to online music stores for paid purchase on January 29.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/3/32/Rihanna_-_Anti.png/220px-Rihanna_-_Anti.png")

a2.lps << [d1, d2, d3, d4, d5, d6, d7, d8]



a3 = Artist.create(name: "Michael Jackson", description: "Michael Joseph Jackson (August 29, 1958 – June 25, 2009) was an American singer, songwriter and dancer. Dubbed the King of Pop, he is regarded as one of the most significant cultural icons of the 20th century and is also regarded as one of the greatest entertainers of all time. Jackson's contributions to music, dance, and fashion, along with his publicized personal life, made him a global figure in popular culture for over four decades.", url: "https://www.amigosvalencia.com/imagenes/act651305530.jpg")

d1 = Lp.create(name: "Got to Be There", description: "Got to Be There is the debut studio album by Michael Jackson, released by Motown on January 24, 1972. It includes the song of the same name, which was released on October 7, 1971, as Jackson's debut solo single. It sold 900,000 copies in the United States and over 3.2 million copies worldwide. The album was later remastered and reissued in 2009 as part of the 3-disc compilation Hello World: The Motown Solo Collection.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/b/b2/Mj1971-got-to-be-there.jpg/220px-Mj1971-got-to-be-there.jpg")
d2 = Lp.create(name: "Ben", description: "Ben is the second studio album by Michael Jackson, released by Motown Records on August 4, 1972, while Jackson was still a member of The Jackson 5. The album received mixed reviews from contemporary music critics. Ben was more successful on the music charts than Jackson's previous studio album, having charted within the top ten on the Billboard 200. Internationally, the album was less successful, peaking at number twelve in Canada, while charting within the top 200 positions in Australia and France.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/1/17/BenMichaelJackson.jpg/220px-BenMichaelJackson.jpg")
d3 = Lp.create(name: "Music & Me", description: "Music & Me is the third studio album by American artist Michael Jackson, released in 1973 on the Motown label, selling two million copies worldwide. The album was reissued in 2009 as part of the 3-disc compilation Hello World: The Motown Solo Collection.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/1/19/Mjmusicandme.jpg/220px-Mjmusicandme.jpg")
d4 = Lp.create(name: "Forever, Michael", description: "Forever, Michael is the fourth studio album by Michael Jackson, released by Motown Records on January 16, 1975. It was generally well received by contemporary music critics. Unlike Jackson's previous studio albums, the album was not commercially successful worldwide. Except for the peak position of number 101 on the Billboard 200 and number 10 on a Billboard component chart in the United States, the album did not chart on any music charts. The album has sold over one million copies worldwide. The album, with the length of over 30 minutes, is credited as having songs with R&B, pop, soul material. Edward Holland, Jr., Brian Holland, Hal Davis, Freddie Perren, Sam Brown III served as producers to Forever, Michael. As part of promotion for the album, three singles were released from Forever, Michael, all of which were moderate commercial successes on the Billboard Hot 100 and other music charts worldwide.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/b/be/Mjforever.JPG/220px-Mjforever.JPG")
d5 = Lp.create(name: "Off the Wall", description: "Off the Wall is the fifth solo studio album by American singer Michael Jackson, released on August 10, 1979 in the United States by Epic Records, and internationally by CBS Records. It was his first album released through Epic Records, the label he would record on until his death roughly 30 years later. Recording sessions took place between December 1978 and June 1979 at Allen Zentz Recording, Westlake Recording Studios, and Cherokee Studios in Los Angeles, California. The record was a departure from Jackson's previous work for Motown Records. Its lyrical themes on the record relate to escapism, liberation, loneliness, hedonism and romance. Several critics observed that Off the Wall was crafted from funk, disco, soft rock, Broadway and pop ballads.", url: "https://upload.wikimedia.org/wikipedia/en/f/f6/Off_the_wall.jpg")
d6 = Lp.create(name: "Thriller", description: "Thriller is the sixth studio album by American singer Michael Jackson, released on November 30, 1982, in the United States by Epic Records and internationally by CBS Records. It explores genres similar to Jackson's previous album, Off the Wall, including pop, post-disco, rock and funk. Recording sessions took place from April to November 1982 at Westlake Recording Studios in Los Angeles, with a production budget of $750,000.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/5/55/Michael_Jackson_-_Thriller.png/220px-Michael_Jackson_-_Thriller.png")
d7 = Lp.create(name: "Bad", description: "Bad is the seventh studio album by American singer and songwriter Michael Jackson. It was released on August 31, 1987 in the United States by Epic Records and internationally by CBS Records, nearly five years after Jackson's previous solo studio album, Thriller. Bad was written and recorded over more than three and a half years, and was the final collaboration between Jackson and producer Quincy Jones. The lyrical themes include media bias, paranoia, racial profiling, romance, self-improvement and world peace.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/5/51/Michael_Jackson_-_Bad.png/220px-Michael_Jackson_-_Bad.png")
d8 = Lp.create(name: "Dangerous", description: "Dangerous is the eighth studio album by American singer Michael Jackson. It was released by Epic Records on November 26, 1991. The album was co-produced by Jackson, Bill Bottrell, Teddy Riley, and Bruce Swedien. Dangerous was Jackson's first album since Forever, Michael (1975) not produced by longtime collaborator Quincy Jones.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/1/11/Michaeljacksondangerous.jpg/220px-Michaeljacksondangerous.jpg")
d9 = Lp.create(name: "HIStory", description: "HIStory: Past, Present and Future, Book I (usually shortened to HIStory) is the ninth studio album by American singer Michael Jackson, released on June 20, 1995. It was Jackson's fifth album released through Epic Records, and the first released on his label MJJ Productions. The album was Jackson's first studio album since his 1991 album Dangerous nearly four years prior, and his first new material to be released since being accused of child sexual abuse in 1993. HIStory consists of two discs: the first, HIStory Begins, is a greatest hits compilation; the second, HIStory Continues, comprises new material written and produced by Jackson and collaborators. The themes include environmental awareness, isolation, greed, suicide, injustice, and Jackson's conflicts with the media.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/3/35/MJ-HIStory.jpg/220px-MJ-HIStory.jpg")
d10 = Lp.create(name: "Invincible", description: "Invincible is the final studio album by American singer Michael Jackson. It was released on October 30, 2001, by Epic Records. Similar to Jackson's previous material, Invincible explores themes such as love, romance, isolation, media criticism, and social issues. It was Jackson's sixth studio album released through Epic, and his last released before his death in 2009.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/9/98/Mjinvincible.jpg/220px-Mjinvincible.jpg")

a3.lps << [d1, d2, d3, d4, d5, d6, d7, d8, d9, d10]


a4 = Artist.create(name: "Elvis Presley", description: "Elvis Aaron Presley (January 8, 1935 – August 16, 1977) was an American singer and actor. Regarded as one of the most significant cultural icons of the 20th century, he is often referred to as the King of Rock and Roll or simply the King.", url: "https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Elvis_Presley_promoting_Jailhouse_Rock.jpg/250px-Elvis_Presley_promoting_Jailhouse_Rock.jpg")

d1 = Lp.create(name: "Elvis Presley", description: "Elvis Presley (released in the UK as Elvis Presley Rock n' Roll) is the debut studio album by American singer and musician Elvis Presley. It was released on RCA Victor, catalogue number LPM-1254, in March 1956. The recording sessions took place on January 10 and January 11 at the RCA Victor recording studios in Nashville, Tennessee, and on January 30 and January 31 at the RCA Victor studios in New York. Additional material originated from sessions at Sun Studio in Memphis, Tennessee, on July 5, August 19 and September 10 of 1954, and on July 11, 1955.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/f/f5/Elvis_Presley_LPM-1254_Album_Cover.jpg/220px-Elvis_Presley_LPM-1254_Album_Cover.jpg")
d2 = Lp.create(name: "Elvis for Everyone! ", description: "Elvis for Everyone! is the eighth studio album by American singer and musician Elvis Presley, issued by RCA Victor in mono and stereo, LPM/LSP 3450, in August 1965. Recording sessions took place over a ten-year span at Sun Studio in Memphis, RCA Studio B in Nashville, Tennessee, and Radio Recorders in Hollywood, California. It peaked at number 10 on the Top Pop Albums chart.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/4/40/Elvis-For-Everyone.jpg/220px-Elvis-For-Everyone.jpg")
d3 = Lp.create(name: "Love Letters from Elvis", description: "Love Letters from Elvis is the fourteenth studio album by American singer and musician Elvis Presley, released in 1971. The album was critically panned upon release, and failed to crack the top 20 of the Billboard album charts but did reach #12 on the US Top Country Albums chart and #7 on the UK best-selling albums chart.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/a/a7/Love-Letters-from-Elvis-Cover.jpg/220px-Love-Letters-from-Elvis-Cover.jpg")
d4 = Lp.create(name: "Raised on Rock", description: "Raised on Rock / For Ol' Times Sake is the nineteenth studio album by American singer and musician Elvis Presley, released in 1973. Along with the album Elvis, it was released after the massive success of Aloha From Hawaii (although the entire Elvis album contained material recorded before the Aloha show). The album sold over one million copies worldwide.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/f/fc/Elvis_Raised_On_Rock.jpg/220px-Elvis_Raised_On_Rock.jpg")
d5 = Lp.create(name: "Moody Blue", description: "Moody Blue is the twenty-fourth and final studio album by American singer and musician Elvis Presley, released by RCA Records in July 1977, less than a month before his death. The album was a mixture of live and studio work, and included the four tracks from Presley's final studio recording sessions in October 1976 and two tracks left over from the previous Graceland session in February 1976. Moody Blue was a previously published hit song recorded at the earlier Graceland session and held over for this album. Also recorded at the February session was She Thinks I Still Care. Way Down became a hit after Presley's death less than one month after this album's publication. The album was certified Gold and Platinum on September 12, 1977 and 2x Platinum on March 27, 1992 by the RIAA.", url: "https://upload.wikimedia.org/wikipedia/en/thumb/2/22/Moody-Blue.jpg/220px-Moody-Blue.jpg")

a4.lps << [d1, d2, d3, d4, d5]
